# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
rooms = [{ price: 7000, room_type: "Deluxe Rooms", rno:"A01" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"A02" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"A03" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"A04" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"A05" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"B01" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"B02" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"B03" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"B04" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"B05" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"C01" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"C02" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"C03" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"C04" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"C05" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"D01" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"D02" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"D03" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"D04" },
        { price: 7000, room_type: "Deluxe Rooms", rno:"D05" },
        { price: 8500, room_type: "Luxury Rooms", rno:"A06" },
        { price: 8500, room_type: "Luxury Rooms", rno:"A07" },
        { price: 8500, room_type: "Luxury Rooms", rno:"A08" },
        { price: 8500, room_type: "Luxury Rooms", rno:"A09" },
        { price: 8500, room_type: "Luxury Rooms", rno:"A10" },
        { price: 8500, room_type: "Luxury Rooms", rno:"B06" },
        { price: 8500, room_type: "Luxury Rooms", rno:"B07" },
        { price: 8500, room_type: "Luxury Rooms", rno:"B08" },
        { price: 8500, room_type: "Luxury Rooms", rno:"B09" },
        { price: 8500, room_type: "Luxury Rooms", rno:"B10" },
        { price: 8500, room_type: "Luxury Rooms", rno:"C06" },
        { price: 8500, room_type: "Luxury Rooms", rno:"C07" },
        { price: 8500, room_type: "Luxury Rooms", rno:"C08" },
        { price: 8500, room_type: "Luxury Rooms", rno:"C09" },
        { price: 8500, room_type: "Luxury Rooms", rno:"C10" },
        { price: 8500, room_type: "Luxury Rooms", rno:"D06" },
        { price: 8500, room_type: "Luxury Rooms", rno:"D07" },
        { price: 8500, room_type: "Luxury Rooms", rno:"D08" },
        { price: 8500, room_type: "Luxury Rooms", rno:"D09" },
        { price: 8500, room_type: "Luxury Rooms", rno:"D10" },
        { price: 12000, room_type: "Luxury Suites", rno:"D11" },
        { price: 12000, room_type: "Luxury Suites", rno:"D12" },
        { price: 12000, room_type: "Luxury Suites", rno:"D13" },
        { price: 12000, room_type: "Luxury Suites", rno:"D14" },
        { price: 12000, room_type: "Luxury Suites", rno:"D15" },
        { price: 12000, room_type: "Luxury Suites", rno:"D16" },
        { price: 12000, room_type: "Luxury Suites", rno:"D17" },
        { price: 12000, room_type: "Luxury Suites", rno:"D18" },
        { price: 12000, room_type: "Luxury Suites", rno:"D19" },
        { price: 12000, room_type: "Luxury Suites", rno:"D20" },
        { price: 12000, room_type: "Luxury Suites", rno:"E01" },
        { price: 12000, room_type: "Luxury Suites", rno:"E02" },
        { price: 20000, room_type: "Presidential Suites", rno:"E03" },
        { price: 20000, room_type: "Presidential Suites", rno:"E04" },
        { price: 20000, room_type: "Presidential Suites", rno:"E05" },
        { price: 20000, room_type: "Presidential Suites", rno:"E06" },
        { price: 20000, room_type: "Presidential Suites", rno:"E07" },
        { price: 20000, room_type: "Presidential Suites", rno:"E08" },
        { price: 20000, room_type: "Presidential Suites", rno:"E09" },
        { price: 20000, room_type: "Presidential Suites", rno:"E10" }]

    Room.create(rooms)